// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ServersideComponent/Navbar/NavbarComponent"; 

import { Toaster } from "react-hot-toast";
import Footer from "@/components/ServersideComponent/Footer/Footer";
import { fetchTopCategories } from "@/api/fetchTopCategories";
import { getNewArrivalProducts } from "@/api/fetchNewArrivalProducts";
import ReduxProviderWrapper from "@/providers/ReduxProviderWrapper";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Cosmectics",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const topCategories = await fetchTopCategories();
  const newArrivals = await getNewArrivalProducts();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${josefinSans.variable} antialiased`}
      >
        <ReduxProviderWrapper>
          <Toaster position="top-right" />
          <Navbar />
          <main className="pt-0">{children}</main>
          <Footer topCategories={topCategories}  newArrivals={newArrivals}  />
        </ReduxProviderWrapper>
      </body>
    </html>
  );
}
