import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ServersideComponent/Navbar/NavbarComponent";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/ServersideComponent/Footer/Footer";
import { fetchTopCategories } from "@/api/fetchTopCategories";
import ReduxProviderWrapper from "@/CartProvider/ReduxProviderWrapper";
import { getCompanySettings, CompanySettings } from "@/api/CompanyApi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Cosmectics",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const topCategories = await fetchTopCategories();
  const companySettingsRes = await getCompanySettings();
  const companyDetails: CompanySettings | undefined =
    companySettingsRes?.result?.[0];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} font-serif antialiased`}
      >
        <ReduxProviderWrapper>
          <Toaster position="top-center" />
          <Navbar companyDetails={companyDetails} />
          <main className="pt-0 bg-white">{children}</main>
          <Footer
            topCategories={topCategories}
            companyDetails={companyDetails}
          />
        </ReduxProviderWrapper>
      </body>
    </html>
  );
}
